axf/urls.py
from django.conf.urls import url

from axf import views

urlpatterns = [
    url(r'^$',views.home,name='home'),
    url(r'^market/$',views.market,name='market'),
    url(r'^cart/$',views.cart,name='cart'),
    url(r'^mine/$',views.mine,name='mine'),
]

mysite19/urls.py
from django.conf.urls import url, include
from django.contrib import admin



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('axf.urls', namespace='axf')),
]

axf/models.py
from django.db import models

# Create your models here.
class Base(models.Model):
    img = models.CharField(max_length=100)
    name = models.CharField(max_length=20)
    trackid = models.CharField(max_length=20)
    class Meta:
        abstract = True


class Wheel(Base):
    class Meta:
        db_table = 'axf_wheel'

    def __str__(self):
        return '{}-{}-{}'.format(self.name,self.trackid,self.img)

axf/views.py
from django.shortcuts import render

# Create your views here.
from axf.models import Wheel


def home(request):
    wheels = Wheel.objects.all()
    return render(request, 'home/home.html', context={
        'wheels': wheels
    })


def market(request):
    return render(request, 'market/market.html')


def cart(request):
    return render(request, 'cart/cart.html')


def mine(request):
    return render(request, 'mine/mine.html')

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
{#给子html的标题坑#}
    {% block title %}
        <title></title>
    {% endblock %}

{#base的css#}
    <link rel="stylesheet" href="{% static 'base/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">

{#給子html的css坑#}
    {% block basecss %}

    {% endblock %}
</head>

<body>

{# 头部#}
{% block header %}
    <header>爱鲜蜂</header>
{% endblock %}


{#給子类的中间内容坑#}
<div class="hidescroll">
    <div id="content">
        {% block content %}

        {% endblock %}
    </div>
</div>




{# 尾部#}
{% block footer %}
    <footer>
        <a href="{% url 'axf:home' %}" class="home">
            <dl>
                <dt> <span></span> </dt>
                <dd> 首页 </dd>
            </dl>
        </a>

        <a href="{% url 'axf:market' %}" class="market">
            <dl>
                <dt> <span></span> </dt>
                <dd> 闪购超市 </dd>
            </dl>
        </a>

        <a href="{% url 'axf:cart' %}" class="cart">
            <dl>
                <dt> <span></span> </dt>
                <dd> 购物车 </dd>
            </dl>
        </a>

        <a href="{% url 'axf:mine' %}" class="mine">
            <dl>
                <dt> <span></span> </dt>
                <dd> 我的 </dd>
            </dl>
        </a>
    </footer>
{% endblock %}




{#base的js#}
<script src="{% static 'base/js/jquery.js'%}"></script>
<script src="{% static 'base/js/jquery.cookie.js'%}"></script>
<script src="{% static 'base/js/bootstrap.js'%}"></script>
<script src="{% static 'base/js/base.js'%}"></script>
{#給子html挖的js坑#}
{% block basejs %}

{% endblock %}

</body>
</html>

templates/cart/cart.html
{% extends 'base/base.html' %}
{% load static %}



{#标题坑#}
    {% block title %}
        <title>AXF | 购物车</title>
    {% endblock %}


{#給子html的css坑#}
    {% block basecss %}
 <link rel="stylesheet" href="{% static 'cart/css/cart.css' %}">
    {% endblock %}




{#給子类的中间内容坑#}
<div class="hidescroll">
    <div id="content">
        {% block content %}
            购物车
        {% endblock %}
    </div>
</div>





{#給子html挖的js坑#}
{% block basejs %}

{% endblock %}

templates/home/home.html
{% extends 'base/base.html' %}
{% load static %}


{#标题坑#}
{% block title %}
    <title>AXF | 首页</title>
{% endblock %}



{#給子html的css坑#}
{% block basecss %}
{#    <link rel="stylesheet" href="{% static 'home/css/swiper.min.css' %}">#}
    <link rel="stylesheet" href="{% static 'home/css/swiper-3.4.2.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/home.css' %}">
{% endblock %}






{#給子类的中间内容坑#}
<div class="hidescroll">
    <div id="content">
        {% block content %}

            <div class="swiper-container">
                <div class="swiper-wrapper">

                    {% for wheel in wheels %}
                        <div class="swiper-slide"><img src="{{ wheel.img }}" alt="{{ wheel.name }}"></div>
                    {% endfor %}

                </div>
                <!-- Add Pagination -->
                <div class="swiper-pagination"></div>
                <!-- Add Arrows -->
                <div class="swiper-button-next"></div>
                <div class="swiper-button-prev"></div>
            </div>

        {% endblock %}
    </div>
</div>


{#給子html挖的js坑#}
{% block basejs %}
{#    <script type="text/javascript" src="{% static 'home/js/swiper.min.js' %}"></script>#}
    <script src="{% static 'home/js/swiper-3.4.2.min.js' %}"></script>
    <script src="{% static 'home/js/home.js' %}"></script>
{% endblock %}

templates/market/market.html
{% extends 'base/base.html' %}
{% load static %}





{#标题坑#}
    {% block title %}
       <title>AXF | 市场</title>
    {% endblock %}


{#給子html的css坑#}
    {% block basecss %}
 <link rel="stylesheet" href="{% static 'market/css/market.css' %}">
    {% endblock %}



{#給子类的中间内容坑#}
<div class="hidescroll">
    <div id="content">
        {% block content %}
            市场
        {% endblock %}
    </div>
</div>





{#給子html挖的js坑#}
{% block basejs %}

{% endblock %}

templates/mine/mine.html
{% extends 'base/base.html' %}
{% load static %}



{#标题坑#}
    {% block title %}
        <title>AXF | 我的</title>
    {% endblock %}


{#給子html的css坑#}
    {% block basecss %}
        <link rel="stylesheet" href="{% static 'mine/css/mine.css' %}">
    {% endblock %}





{#給子类的中间内容坑#}
<div class="hidescroll">
    <div id="content">
        {% block content %}
            我的
        {% endblock %}
    </div>
</div>





{#給子html挖的js坑#}
{% block basejs %}

{% endblock %}